language: elixir
elixir:
  - 1.3.4
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.3
  - 19.3
  - 20.2

env:
  - STRICT=true
  - STRICT=false

matrix:
  exclude:
    - elixir: 1.6
      env: STRICT=false
    - elixir: 1.3.4
      env: STRICT=true
    - elixir: 1.4
      env: STRICT=true
    - elixir: 1.5
      env: STRICT=true
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 20.2

script:
  - if [ "$STRICT" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - mix credo
  - if [ "$STRICT" = "true" ]; then mix dialyzer; fi
  - if [ "$STRICT" = "true" ]; then mix format --dry-run --check-formatted; fi

cache:
  directories:
    - .mix
    - _build
